export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const LOADING_CATEGORIES_SUCCESS = 'LOADING_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_STORE_SUCCESS = 'FETCH_STORE_SUCCESS';
export const LOADING_STORE_SUCCESS = 'LOADING_STORE_SUCCESS';
export const FETCH_STORE_ERROR = 'FETCH_STORE_ERROR';

export const FILTER_STORE_SUCCESS = 'FILTER_STORE_SUCCESS';
export const FILTER_STORE_ERROR = 'FILTER_STORE_ERROR';

